### ISSUE TITLE
[API Reference] Removing [Beta] from Qualifications

### ISSUE THREAD

**Issue by janiksam** [voucherifyio/voucherify-openapi#474]
@p-zielinski 

do zdjęcia Beta z Qualifications (3) są potrzebne 3 kroki

1. Usunąć `[Beta]` z title w OpenAPI do trzech endpointów (jeden dummy)
2. Usunąć `[Beta]` z .md 3 plików 
3. Usunąć kolejny kod z [block] w .md plikach

```css
h1::after {
    content: "BETA";
    background-color: rgb(237, 117, 71);
    color: rgb(255, 255, 255);
    border-radius: 2rem;padding: 8px 13px 8px;
    white-space: nowrap;font-size:12px;
}
```
